# Generated by Django 4.2.17 on 2025-02-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
