# Generated by Django 4.2.17 on 2025-02-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usertoken_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='username',
            new_name='user',
        ),
    ]
