# Generated by Django 4.2.17 on 2025-02-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_username_usertoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='email',
        ),
    ]
