# Generated by Django 4.2.17 on 2025-01-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=100)),
                ('pre_trained_model', models.CharField(max_length=100)),
                ('task_type', models.CharField(max_length=100)),
                ('mAP', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('model_size', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
