# Generated by Django 4.2.17 on 2025-01-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('pre_model_name', models.CharField(max_length=100)),
                ('dataset_name', models.CharField(max_length=100)),
                ('task_type', models.CharField(max_length=132)),
                ('status', models.CharField(max_length=16)),
                ('epoch', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('image_size', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('model_size', models.CharField(max_length=32)),
            ],
        ),
    ]
