# Generated by Django 4.2.17 on 2025-02-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEpochModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('epoch_number', models.IntegerField()),
                ('mAP50', models.FloatField()),
                ('mAP95', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('training_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingmodel')),
            ],
            options={
                'ordering': ['training_model', 'epoch_number'],
            },
        ),
    ]
